MProj/force-app/main/default/objects/Anomaly__c/Anomaly__c.object-meta.xml
<CustomObject>
    <label>Anomaly</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Anomaly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MProj/force-app/main/default/objects/Anomaly__c/fields/Weather__c.field-meta.xml
<CustomField>
    <fullName>Weather__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weather</label>
    <referenceTo>Weather__c</referenceTo>
    <relationshipLabel>Anomalies</relationshipLabel>
    <relationshipName>Anomalies</relationshipName>
    <type>Lookup</type>
</CustomField>

MProj/force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weater</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MProj/force-app/main/default/classes/WeatherTriggerHandler.cls
public with sharing class WeatherTriggerHandler {

    public static void handleBeforeInsert(List<Weather__c> newList){}

    public static void handleAfterInsert(List<Weather__c> newList) {
        Anomaly__c a = new Anomaly__c();
		AnomalyDetector ad = new AnomalyDetector();
        for(Weather__c weather:newList) {
            List<Anomaly__c> l = new List<Anomaly__c>();
            l = ad.detectAnomaly(weather);
            if(!l.isEmpty()) {
                insert l;
            }
	        }
        //Code here 
        //Use AnomalyDetector to detect an anomaly
        //Use SOQL to get City record information
        //insert Anomalies
        //update City
    }

    public static void handleBeforeUpdate(List<Weather__c> newList, List<Weather__c> oldList){}

    public static void handleAfterUpdate(List<Weather__c> newList, List<Weather__c> oldList){}

    public static void handleBeforeDelete(List<Weather__c> oldList){}

    public static void handleAfterDelete(List<Weather__c> oldList){}
}